### PR TITLE
Fixed issue resulting from change to user/me api

### PR DESCRIPTION
**Pull request by cbartondock**
Addresses [issue 3](https://github.com/deemstone/print2Boox/issues/3) and [issue 2](https://github.com/deemstone/print2Boox/issues/2)

### CODE REVIEW

**Comment by deemstone** [comment]
Thanks for your help! And feel sorry to the delay 😔 I've been exhausted by work these weeks.
I will try to merge this and release 0.0.8 this weekend.

**Comment by cbartondock** [comment]
No worries at all, if anything I should be thanking you for giving me a productive way to procrastinate!

**Comment by cbartondock** [comment]
Well shoot. This was working for me last night (printing) but this morning I tried to do a different document and got 
`InvalidAccessKeyIdError: The OSS Access Key Id you provided does not exist in our records.`

**Comment by cbartondock** [comment]
Seems they may have changed multiple parts of the API

**Comment by cbartondock** [comment]
Logged out and logged in again and it worked. Definitely fishy. I think they might be changing the OSS Access Key periodically, so it's insufficient for the extension to get it once

**Comment by cbartondock** [comment]
Everything seems to be working now, although currently I am reobtaining the oss key each push. It seems that this might be necessary now.

**Comment by cbartondock** [comment]
If you have the chance to merge the PR I'd appreciate it - it's working well for me.

**Comment by deemstone** [comment]
Thank you ! I will add some UI tip before release new version. soon.

**Comment by cbartondock** [comment]
Great! Thanks for all your work.

**Pull request merged**
